### PR TITLE
Redesign Web UI

### LINKED ISSUE #48: Download button not Working
I can upload files and everything but after I go to the download link, The button doesn't work at all. I tried with 1kb file to 200mb file, Nothing works

### LINKED ISSUE #52: failed to share
Failed to share file: NotAllowedError: Failed to execute 'share' on 'Navigator': Must be handling a user gesture to perform a share request.

### PR DESCRIPTION
**Pull request by tris203**
Migrate styling from combination of MUI/Bootstrap to tailwind
Adjust layout to be mobile first for better display
Implement some UI changes to be more mobile friendly (More notification bars, and less pop ups)
Adjust share copy method to work in more browsers and be more accessible

Upgrade Client Rendering API to React 18 method
Remove unneeded dependencies and update remaining ones

work on #9 
fixes #52 
fixes #48

### CODE REVIEW

**Comment by tris203** [comment]
This would go someway towards
issue #9 

There would need to be some changes in the file downloading section but im happy to help

**Comment by DisboxApp** [comment]
Wow!

First of all, thank you so much for the contribution!
It is hugely appreciated.

I will look at this very soon and will work on merging this ASAP.

**Comment by tris203** [comment]
No problem. If you want to talk any of it through let me know

I've made a few decisions through the changes but happy to alter/justify them

**Comment by tris203** [comment]
This also addresses #52 
Also addresses #48 (Or will show a message warning the user that downloads are not supported in their browser)

**Comment by DisboxApp** [comment]
Hey! I really like the changes here made towards sharing working for more browsers and the changes made towards mobile devices.

However, I've been planning (but couldn't get to it myself, so I really appreciate this PR) a UI redesign for a while, and I have a different direction in mind.

I'm thinking we should completely ditch the verbal buttons for each file and go with a google-drive-like approach.
Actions should either appear as icons on hover, or appear when right-clicking  (or using a button to open the menu on mobile). They should also appear at the top when one or more files are selected (using the datagrid's checkboxes or with CTRL and SHIFT which is already supported) which will finally allow doing operations on multiple files together like moving and deleting.

What do you think?

**Comment by tris203** [comment]
Fully agree

As said in my second comment, I haven't touched the data grid yet. I just wanted to get a feel for the appetite for a UI overhaul and better mobile support

It would be nice to get something merged to agree on a technology stack (Eg is tailwind and Vite okay) then we can work on smaller parts in isolation as features

Makes the PRs much more manageable as they stop being huge monoliths

**Pull request closed without merging**
